export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'; //eslint-disable-line
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const CURRENT_USER_INFO = 'CURRENT_USER_INFO';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';


export const CREATE_DOCUMENTS_SUCCESS = 'CREATE_DOCUMENTS_SUCCESS';
export const LOAD_DOCUMENTS_SUCCESS = 'LOAD_DOCUMENTS_SUCCESS';
export const UPDATE_DOCUMENTS_SUCCESS = 'UPDATE_DOCUMENTS_SUCCESS';
export const DELETE_DOCUMENTS_SUCCESS = 'DELETE_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENT_SUCCESS = 'FETCH_DOCUMENT_SUCCESS';
export const SEARCH_DOCUMENTS_SUCCESS = 'SEARCH_DOCUMENTS_SUCCESS';



